# THIS FILE HAS BEEN AUTOGENERATED. To update:
# 1. modify the `_deps` dict in setup.py
# 2. run `make deps_table_update``
deps = {
    "torch": "torch==1.13.0",
    "transformers": "transformers==4.31.0",
    "diffusers": "diffusers==0.14.0",
}
